### ISSUE TITLE
Legit

### ISSUE THREAD

**Issue by CookieHosting** [nxllone/Auto-MoonSec-v3-Dumper#3]

**Comment by osp54** [comment]
https://www.virustotal.com/gui/file/ef96103782ed9d4f5a1b179f7a6d87c3baf8d9f58d81e6be4783e2680fe9b4ac

**Comment by nxllone** [comment]
> https://www.virustotal.com/gui/file/ef96103782ed9d4f5a1b179f7a6d87c3baf8d9f58d81e6be4783e2680fe9b4ac

Not the same file

**Comment by nxllone** [comment]
Issue closed

**Comment by osp54** [comment]
> > https://www.virustotal.com/gui/file/ef96103782ed9d4f5a1b179f7a6d87c3baf8d9f58d81e6be4783e2680fe9b4ac
> 
> Not the same file

Complete idiot
